---
abstract: 'Mojolicious command for generating cpanfile'
author:
  - 'Yogesh Pandit <yogeshp08@gmail.com>'
build_requires:
  Test::Exception: 0.31
  Test::File: 1.34
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Command-generate-cpanfile
requires:
  Mojolicious: 3.89
version: 0.1.0
